version: "3"

services:

  cachingmanagerauth:
    ports:
      - "8082:8082"
    image: docker-cachingmanagerauth
    build:
      context: ./CachingManagerAuthToken
      dockerfile: Dockerfile
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-gatewayserver:8080/eureka/
    tty: false
    depends_on:
      - gateway
    networks:
      - cache-manager

  gateway:
    ports:
      - "8080:8080"
    image: docker-gateway
    build:
      context: ./GateWay
      dockerfile: Dockerfile
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-gatewayserver:8080/eureka/
    tty: false
    networks:
      - cache-manager

networks:
  cache-manager:
    driver: bridge