version: "3"

services:

  cachingmanagerauth:
    ports:
      - "8082:8082"
    image: docker-cachingmanagerauth
    build:
      context: ./CachingManagerAuthToken
      dockerfile: Dockerfile
    hostname: cachingmanagerauthservice
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-gatewayserver:8080/eureka
    depends_on:
      - gateway
    networks:
      - cache-manager

  zuul:
    ports:
      - "9091:9091"
    image: docker-zuulservice
    build:
      context: ./Zuul
      dockerfile: Dockerfile
    hostname: zuulservice
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-gatewayserver:8080/eureka
    depends_on:
      - gateway
    networks:
      - cache-manager

  gateway:
    ports:
      - "8080:8080"
    image: docker-gateway
    build:
      context: ./GateWay
      dockerfile: Dockerfile
    hostname: eureka-gatewayserver
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-gatewayserver:8080/eureka
    networks:
      - cache-manager

networks:
  cache-manager:
    driver: bridge