version: "3.6"

services:

  redis:
    image: "redis:alpine"
    container_name: redis
    ports: ["6379"]
    networks:
      - cache-manager

  cachingmanager:
    container_name: cachingmanagerservice
    image: docker-cachingmanager
    build: 
      context: ./CachingManager
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    hostname: cachingmanagerservice.cache.com
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-gatewayserver:8080/eureka
    depends_on:
      - gateway
    links:
      - "redis:localhost"
    networks:
      - cache-manager

  cachingmanagerauth:
    container_name: cachingmanagerauthservice
    image: docker-cachingmanagerauth
    build:
      context: ./CachingManagerAuthToken
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    hostname: cachingmanagerauthservice.cache.com
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-gatewayserver:8080/eureka
    depends_on:
      - gateway
    networks:
      - cache-manager

  zuul:
    container_name: zuulservice
    image: docker-zuulservice
    build:
      context: ./Zuul
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    hostname: zuulservice.cache.com
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-gatewayserver:8080/eureka
    depends_on:
      - gateway
    networks:
      - cache-manager

  gateway:
    container_name: eureka-gatewayserver
    image: docker-gateway
    build:
      context: ./GateWay
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    hostname: eureka-gatewayserver
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-gatewayserver:8080/eureka
    networks:
      - cache-manager

networks:
  cache-manager:
    driver: bridge