version: "3.6"

services:

  gateway:
    build: ./GateWay
    container_name: docker-gateway
    ports:
      - "8080:8080"
    hostname: eureka-gatewayserver
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-gatewayserver:8080/eureka
    networks:
      - cache-manager

  cachingmanagerauth:
    build: ./CachingManagerAuthToken
    container_name: docker-cachingmanagerauth
    ports:
      - "8082:8082"
    hostname: cachingmanagerauth
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-gatewayserver:8080/eureka
    networks:
      - cache-manager
    depends_on:
      - gateway

networks:
  cache-manager:
