version: '3'
services:
  cachingmanager:
    build: .
    ports:
     - "8081:8081"
    links:
     - "redis:localhost"
    networks:
     - front-tier
     - back-tier
      
  redis:
    image: "redis:alpine"
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier
      
  networks:
    front-tier:
    back-tier:
    